version: '3.7'

services:
  mongodb:
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=skoredb_dev
      - MONGO_INITDB_ROOT_USERNAME=extensions
      - MONGO_INITDB_ROOT_PASSWORD=extensions
    image: mongo:4.2.8
    restart: always
    ports:
      - 27017:27017
    command: mongod --setParameter notablescan=1

  redis:
    command: redis-server --requirepass redispassword
    container_name: redis
    image: redis:5.0.9-alpine
    ports:
      - 6379:6379

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm.json
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/packages/keycloak/realm.json:/tmp/realm.json
