version: '3.8'

services:
  redis:
    command: redis-server --requirepass redispassword
    container_name: redis
    image: redis:5.0.9-alpine
    ports:
      - 6379:6379

  keycloak:
    image: jboss/keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm.json
    ports:
      - 8080:8080
    volumes:
      - ${PWD}/packages/keycloak/realm.json:/tmp/realm.json
