export enum PubSubTypeEventEnum {
  'io.skore.events.content' = 'io.skore.events.content',
  'io.skore.events.content.live_course' = 'io.skore.events.content.live_course',
  'io.skore.events.session' = 'io.skore.events.session',
  'io.skore.events.enrollment' = 'io.skore.events.enrollment',
  'io.skore.events.user' = 'io.skore.events.user',
  'io.skore.events.team' = 'io.skore.events.team',
  'io.skore.events.messaging.message' = 'io.skore.events.messaging.message',
  'io.skore.events.messaging.postback' = 'io.skore.events.messaging.postback',
  'io.skore.events.messaging.conversation' = 'io.skore.events.messaging.conversation',
  'io.skore.events.messaging.intent' = 'io.skore.events.messaging.intent',
  'io.skore.events.notification' = 'io.skore.events.notification',
  'io.skore.commands.notification' = 'io.skore.commands.notification',
  'io.skore.commands.outbound' = 'io.skore.commands.outbound',
  'io.skore.commands.integration' = 'io.skore.commands.integration',
  'io.skore.commands.space' = 'io.skore.commands.space',
}

export enum PubSubActionEnum {
  send_push = 'send_push',
  attended = 'attended',
  accessed = 'accessed',
  partial_consumed = 'partial_consumed',
  consumed = 'consumed',
  completed = 'completed',
  deleted = 'deleted',
  search = 'search',
  reseted = 'reseted',
  commented = 'commented',
  ping = 'ping',
  delivered = 'delivered',
  received = 'received',
  read = 'read',
  sent = 'sent',
  triggered = 'triggered',
  send_notification = 'send_notification',
  base_notification_created = 'base_notification_created',
  base_notification_dispatch = 'base_notification_dispatch',
  created = 'created',
  reindex = 'reindex',
  enrollment_file_uploaded = 'enrollment_file_uploaded',
  subscription_row_processed = 'subscription_row_processed',
}
