/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ContentAccessedEvent = ContentEvent &
  UserEvents & {
    element_type?: "content";
    element_action?: "accessed";
    [k: string]: unknown;
  };
/**
 * Events related to content must have a specific content associated. This includes the type of content and the action taken on it.
 */
export type ContentEvent = Events & {
  /**
   * Type of action taken on the content (e.g., accessed, consumed).
   */
  element_action: "accessed" | "consumed" | "completed" | "attended";
  /**
   * Type of the content element (e.g., content, mission, space).
   */
  element_type: "content" | "mission" | "space";
  /**
   * Unique identifier for the content element.
   */
  element_id: string;
  [k: string]: unknown;
};
/**
 * Basic validation for a user event. It specifies which user initiated the event and through which session.
 */
export type UserEvents = Events & {
  /**
   * Identifier for the user who initiated the event.
   */
  user_id: number;
  meta?: {
    /**
     * Session identifier in which the event occurred, can be null.
     */
    session_id?: string | null;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};
