name: On pull request

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pr_analysis:
    name: PR Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check PR title
        uses: amannn/action-semantic-pull-request@v5.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          subjectPattern: ^(?![A-Z]).+$

      - name: Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

      - name: Application cache
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ./dist
          key: ${{ runner.os }}-build-${{ github.sha }}

      - name: Dependencies
        run: npm i

      - name: Run lint
        run: npm run lint

      - name: Up the containers
        run: docker-compose up -d

      - name: Tests
        run: npm run test
